# Generated by Django 3.1.1 on 2020-09-30 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_Name', models.CharField(default='', max_length=100)),
                ('med_Type', models.CharField(choices=[('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection')], default='', max_length=100)),
                ('num_of_med', models.CharField(default='', max_length=100)),
                ('choi', models.CharField(choices=[('PM', 'PM'), ('TM', 'TM')], default='', max_length=100)),
                ('m_count', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], default='', max_length=100)),
                ('m_time', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
