# Generated by Django 3.1.1 on 2020-10-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meddata',
            name='m_time',
            field=models.DateField(),
        ),
    ]
