# Generated by Django 3.1 on 2020-08-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0004_auto_20200821_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='meddata',
            name='category',
            field=models.CharField(choices=[('tablet', 'tablet'), ('syrup', 'syrup')], default='', max_length=200),
        ),
    ]
