# Generated by Django 3.1 on 2020-08-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0005_meddata_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='meddata',
            name='course',
            field=models.CharField(choices=[(1, 'Daily'), (2, 'Alternate days'), (3, 'Weekly Once'), (4, 'Weekly Twice')], default='', max_length=200),
        ),
    ]
