# Generated by Django 3.1 on 2020-08-27 13:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0007_auto_20200827_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='meddata',
            name='when',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Morning'), (2, 'Noon'), (3, 'Evening'), (4, 'Night')], default='', max_length=7),
        ),
    ]
