# Generated by Django 3.1 on 2020-08-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0008_meddata_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meddata',
            name='when',
        ),
        migrations.AlterField(
            model_name='meddata',
            name='Mrg_med',
            field=models.DateTimeField(),
        ),
    ]
